### ISSUE TITLE
I'm getting no data from API... Where do I get the car data from?

### ISSUE THREAD

**Issue by ipalakchopra** [sathyaprakash195/sheycars-udemy#1]

**Comment by iritikkumar** [comment]
Same Problem. Did you figure out?

**Comment by network9999** [comment]
> Same Problem. Did you figure out?

Can someone please share the cars.json file? if u guys have.......

**Comment by avinash1371** [comment]
is it working ?

**Comment by shivasaidharreddy** [comment]
No did you got I am only in login page
